# name of LLM model, 'custom' for custom model
llm: xop3qwen1b7
# path for item data
item_path: data/item.csv
# path for user data
user_path: data/user_1000.csv
# path for relationship data
relationship_path: data/relationship_1000.csv
# path for save interaction records
interaction_path: data/interaction.csv
# directory name for checkpoint of recommender system model, if not specified, the model will not be saved
ckpt_path: data/ckpt
# directory name for faiss index
index_name: data/faiss_index
# simulator directory name for saving and restoring, if not specified, the simulator will not be saved
simulator_dir: null # output/simulator
# data/simulator
# simulator restoring name
simulator_restore_file_name:
# random seed
seed: 2023
# recommender system model
rec_train: True
rec_model: SimGCL
n_layers: 3       # number of GCN layers, default is 3
eps: 0.1      # noise perturbation size
lamda: 0.5  # contrastive loss weight
tau: 0.2      # InfoNCE temperature coefficient
epoch_num: 500 # train epoch number for recommender system model
batch_size: 2048 # batch size for recommender system model
embedding_size: 128 # embedding size for recommender system model
lr: 0.001 # learning rate for recommender system model
neg_count: 10 # negative sampling count for BPR (1:N)
use_content_embedding: True # whether to use content embedding for recommender system model
text_embedding_size: 1024 # size of text embedding(sentence embedding)
# number of epochs
round: 30
# number of agents, which cannot exceed the number of user in user.csv
agent_num: 1000
agent_start_offset: 0
# number of items to be recommended in one page
page_size: 5
# temperature for LLM
temperature: 0
# maximum number of tokens for LLM
max_token: 8000
# execution mode, serial or parallel
execution_mode: parallel
parallel_workers: 40
# time interval for action of agents. The form is a number + a single letter, and the letter may be s, m, h, d, M, y
interval: 1d
# number of max retries for LLM API
max_retries: 100
# verbose mode
verbose: True
# threshold for agent num
active_agent_threshold: 1000
# method for choose agent to be active, random, sample, or marginal
active_method: random
# propability for agent to be active
active_prob: 1
# implementation of agent memory, recagent or GenerativeAgentMemory
agent_memory: recagent
recagent_memory: recagent
# list of api bases for LLM API, None for running locally of default OpenAI API Base
api_bases:
  # - http://maas-api.cn-huabei-1.xf-yun.com/v1
  - https://maas-api.cn-huabei-1.xf-yun.com/v2
  # - https://maas-api.cn-huabei-1.xf-yun.com/v2
# list of api keys for LLM API or model path of open-sourced LLM running locally
api_keys:
  # - sk-W5q54x1OZfiCVg1I1443E3A138F747Ce9c8247E2C0E7C190
  - 546670836ad62b55503a40c82825ef61:Mjg3ZWQwNWIyMGZkNWMxZTJhYTI4MjU3
  # - 7a166059f77a5f9faca01ae584b5d4a3:NGJkYTM2ZjZkYjM1ODNkOGViOWEyNWQ5
# num of random recommendation, 1,3,5
rec_random_k: 0
# ratio of random friends, 1,3,5
social_random_k: 0
all_interests:
  - "documentaries"
  - "sci-fi movies"
  - "classic movies"
  - "comedy movies"
  - "family-friendly movies"
  - "action movies"
  - "thriller movies"
  - "romantic movies"
generate_interests: true

# predict_social_each_round: True
# predict_social_threshold: 0.9